parameters:
#    website_market_place.example.class: Website\MarketPlaceBundle\Example

services:
#    website_market_place.example:
#        class: %website_market_place.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
